# Generated by Django 2.2.7 on 2019-12-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('desc', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
