# Generated by Django 2.2.7 on 2019-12-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20191211_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_model',
            name='dat',
            field=models.DateTimeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback_model',
            name='desc',
            field=models.CharField(default=False, max_length=500),
        ),
    ]
