# Generated by Django 2.2.7 on 2019-12-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20191211_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback_model',
            name='dat',
        ),
        migrations.AddField(
            model_name='registration',
            name='image',
            field=models.FileField(default=False, upload_to='vinod'),
        ),
    ]
