# Generated by Django 2.2.6 on 2019-12-12 18:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20191211_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('courses', multiselectfield.db.fields.MultiSelectField(choices=[('python', 'PYTHON'), ('java', 'JAVA'), ('.net', '.NET')], max_length=100)),
                ('faculty', multiselectfield.db.fields.MultiSelectField(choices=[('vinod', 'VINOD'), ('sivala', 'SIVALA'), ('kumar', 'KUMAR')], max_length=100)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='feedback_model',
            name='dat',
        ),
    ]
